### ISSUE TITLE
Make `sources.nix` configurable

### ISSUE THREAD

**Issue by nmattia** [nmattia/niv#134]
Until now I've refused to add configuration to `sources.nix` because I really like:

``` nix
let sources = import ./nix/sources.nix; in ...
```

and because in _most cases_ it shouldn't have to be configurable. Having to pass in an empty attrset `{}` in _most cases_ is really not nice. However after discussions with @zimbatm and @NinjaTrappeur I've realized we could have e.g. this:

``` nix
let sources = (import ./nix/sources.nix).__configure { useBuiltinFetchers = false; }; in ...
```

Here most users will never have to care about the configuration, but if you need to tweak how packages are fetched, you can feel free to go for it. I have a POC here: https://github.com/nmattia/niv/blob/b69df92ce13f3b9f9d5344b24ecde6ae945c41d6/nix/sources.nix

I'm thinking about having the following configuration fields:

* `useBuiltinFetchers`: specifies whether `builtins.fetchurl` _et a._ should be used, defaulting to `true`. Hydra users can set it to `false`. Would solve #46 @nlewo and we could get rid of `builtin-tarball` @michaelpj . This also solves some opaque infinite recursion errors due to the heuristics we use for figuring out `<nixpkgs>`.
* `sourcesJson`: the path to the `sources.json` which would (partially) solve #102 
* `fetchers`: a function `name: spec: fetcher: ...` which fetches the `spec` (the attrset coming from `sources.json`), or just returns `fetcher spec` if no special fetcher is needed. This would solve #130 @tfc and #58 @roberth (at least for the case without submodules).

Thoughts?

**Comment by michaelpj** [comment]
> Having to pass in an empty attrset {} in most cases is really not nice.

I don't see this as a big deal. People do this all the time when importing `nixpkgs` or doing `callPackage`. I remember actually doing a double-take the first time I saw an import *without* an attrset argument afterwards!

On the other hand, I have no idea what this magic `__configure` thing is. Somehow it affects how the thing is imported?

My vote goes for boring functions and arguments :)

> useBuiltinFetchers

I don't think this should be a global toggle. My experience is that you want to use the builtin fetchers quite deliberately for specific dependencies, if at all. So it works much better as just "another fetcher" and would be a pain if anything as a global toggle.

> fetchers

I like the idea of just letting people define their own fetchers. My first thought is composability: what happens when e.g. I want to share a special fetcher with people in my company? Then I need to fetch that source and import it before I can use it. This is a very similar problem to the [problem I have](https://github.com/nmattia/niv/issues/46#issuecomment-495310266) with nixpkgs.

I wonder whether there would be some utility in having some "bootstrap" sources that get fetched first and are available to the main fetchers?

**Comment by michaelpj** [comment]
I made a POC in https://github.com/nmattia/niv/pull/137, which IMO works quite nicely.

**Comment by nmattia** [comment]
Thanks so much @michaelpj ! I had a quick look but that wasn’t enough to fully wrap my head around the idea, I’ll give more feedback tomorrow!

**Comment by michaelpj** [comment]
It might not make much sense 😅 I can also push my examples, tbh that's probably a good idea.

**Comment by zimbatm** [comment]
Not following closely but I have a few observations I want to share:

Most of the time, I only want to use the builtin fetcher to bootstrap nixpkgs. The rest can be using build fetchers since they are faster to use (in my experience). The only other reason to use a builtin fetcher would be if it requires some access credentials that are available in my user environment.

I want to avoid evaluating nixpkgs twice because it's slow and takes a lot of memory.

I usually want to be able to initialize nixpkgs with my own custom config and overlays. So I want a way to get the nixpkgs version from niv, initialize it, and then pass it back to niv to use with the build fetchers.

One possible implementation of this could be to pass the nixpkgs initializers to niv and let niv to the bootstrapping internally:
```nix
let pkgs = import ./nix/sources.nix (sources: {
  config = {};
  overlays = [ sources.home-manager ];
});
in pkgs
```

Or externally:
```nix
let
  sourcesBuiltins = import ./nix/sources.nix {};
  pkgs = import sourcesBuiltins.nixpkgs {
    config = {};
    overlays = [
      (_: super: { sources = import ./nix/sources.nix { pkgs = super; }; })
      sourcesBuiltins.home-manager
    ];
  };
in
  pkgs
```

Something like that.

**Comment by nmattia** [comment]
Ok, had some time to dig more into it. I like it! I'd like to retain the interface of https://github.com/nmattia/niv/issues/134#issue-514198558 though, so we could pass the overlays as

``` nix
let sources = (import ./nix/sources.nix).__configure { overlays = [ ... ]; }; in ...
```

or maybe even have two:

``` nix
let 
  sources = import ./nix/sources.nix;
  sourcesSimple = sources.__configure { useBuiltinFetchers = true; };
  sourcesMoreCustomizable = sources.__overlays [ overlay1 overlay2 ];
in ...
```

since the former can be implemented in terms of the latter. That way we can use overlays when necessary (though is it really necessary?), we don't break backwards compatibility and finally we can still use the simple import.

**Comment by michaelpj** [comment]
I prefer the explicit argument passing to the magic attribute, but I'd live. If we're going to have one, let's just have one. I think a simple interface and an advanced interface are fine, but multiple advanced interfaces is too much.

> That way we can use overlays when necessary (though is it really necessary?)

Apart from the use-cases i gave, I'm pretty sure the overlays approach is powerful enough to let people do whatever they want. So that avoids us coming back to this issue when someone has some weird new thing they want to do.

Having some shortcut options for common things also seems fine, although I'm not sure what we'd have. I still think the global builtin fetcher toggle is questionable. However, we can add those on top of the overlays easily enough if some patterns become very common!

**Comment by roberth** [comment]
You could define `sources.__functor` to keep the invocation simple (e.g. `sources {}`) and still be backwards compatible. Basically any new function interface you come up with can be layered on top of the current API this way.

This is a good thing, because it means you can design the new sources.nix interface from scratch, as long as it's a function!

You can even have a backward compatible deprecation of the attrset interface this way.

**Comment by nmattia** [comment]
ok, I really like this overlay + functor solution. Gonna take a stab.

**Comment by leotaku** [comment]
Maybe this could be combined with the efforts currently going on in #132? I think it would be quite good UX to have `sources.nix` be something like this:

```nix
let
  callSources =
    builtins.fetchUrl "https://github.com/nmattia/niv/blob/MY_VERSION/nix/api.nix";
in

callSources ./sources.json {
  someConfigureArgs = "someValue";
}
```

`callSources` in this case returns a special attrs that can be customized further using e.g. `__configure` or `__functor`. I'm just spitballing here, but I hope my suggestion is relevant to the discussion.

**Comment by michaelpj** [comment]
Did you decide not to go with the overlay solution in the end?

**Comment by nmattia** [comment]
@michaelpj that's still the idea! Given that the overlay approach is pretty powerful and low-level, I didn't want to make it the only option. It'll look something like this:

``` nix
let sources = import ./nix/sources.nix { sourcesFile = ...; overlay = ... ; } ; in ...
```
