### ISSUE TITLE
Command line attribute `rev` is ignored

### ISSUE THREAD

**Issue by nlewo** [nmattia/niv#36]
The rev attribute is ignored when provided on CLI.

Considering `niv add NixOS/nixpkgs -a rev=plop`, the `sources.json` should contains `rev=plop` while rev have been updated according to the `--branch` attribute.

Specifying a `rev` attribute is useful when switching a project to Niv because it allows to introduce Niv without changing what is actually built.

**Comment by nmattia** [comment]
Indeed, this should be `whenNotSet` : https://github.com/nmattia/niv/blob/c2698b0780b783880e0b1a520723948fe3b5c26a/Main.hs#L239

Nice catch! Will patch soon.

**Comment by michaelpj** [comment]
It's a little more awkward than that. This is the bit that actually makes `niv update` do an update! I think that:
- `completePackageSpec` should *not* update the rev (i.e. should use `whenNotSet`
- We should have some other `updatePackageSpec` function that we use instead of `completePackageSpec` in `cmdUpdate`

**Comment by michaelpj** [comment]
It would also be nice if `niv update -a rev=<blob>` would update to that revision, whereas currently it just updates to the latest regardless.

**Comment by nmattia** [comment]
This issue actually led me down a terribly deep rabbit hole: https://github.com/nmattia/niv/compare/nm-refactor (which is also aimed at making #35 nicer and hence blocking it). Hoping to find some time to finish things up soon... Worst case, Zurihac.
