### ISSUE TITLE
non-nix deployment workflow/toolchain

### ISSUE THREAD

**Issue by abathur** [nmattia/niv#42]
Hi @nmattia,

Your approach here reminded me of a maybe-out-of-scope problem I've been stewing on. Just hoping to air it out and get your thoughts. My notes are very context-specific, but I suspect this is a fairly general problem that manifests differently for various language/toolchain combinations.

Over the past ~year I've been moving from VMs to Nix development environments for more and more of my projects, but I've got a workflow issue with a Python project that has its dependencies installed via pip for both CI and in production. (CI uses `requirements_dev.txt`, production uses `requirements_common.txt`, both also call `requirements_common.txt`)

The initial generation of a working {shell,requirements}.nix to install the Python dependencies was a bit cumbersome, largely because it involved learning and specifying sub dependencies. It works well with the work invested, but I also feel like I'm sitting on a future maintenance chore. The pip requirements files specify ~35 packages, a handful of which are sub-dependencies that needed to be explicitly pinned at some point; requirements.nix specifies 77 packages and updates to any given package could either cause dependency drift or require manually plumbing the sub-dependency network for updates. 

Ideally I could offload most of this dependency work on nixpkgs, but I'm a little daunted by the (perhaps incorrectly?) perceived complexity of maintaining reproducibility between packages from one or more nix channel and a list of mostly-version-pinned pip packages. Nix cuts a lot of small frictions out of my workflow, but one cost has been giving up a single authoritative list of dependencies. 

I've made notes here and there about writing a few bash scripts to solve some acute issues. For example, I could address single source-of-truth on dependencies by installing pip and adding a script step to the shell.nix that uses pip to export the list of nix-installed Python packages, filters out everything that doesn't match a list, and plugs them back into a requirements.txt template. But, these also feel like very small/local fixes to frictions that I assume others also experience...

1. I've felt for a few months like either I or the Nix ecosystem may be missing some combination of generic/language-specific tools for bi-directional dependency workflows. I'm curious what you think about the problem generally, especially if you think I'm overlooking or overthinking some things.

2. It looks like niv is working on the "inbound" direction in a generic way that made me think it might be well-positioned as a nexus for building up smaller language/ecosystem-specific tools. If so, it might vastly simplify their work/scope and make it more likely that the whole Nix ecosystem can benefit from robust tools for many languages. Inbound tools (analogs of the many x2nix efforts) could handle importing packages from various ecosystem-idiomatic formats and hand them off to niv. Outbound tools (which might or might not be bundled with the inbound tools) could handle writing the same.

**Comment by nmattia** [comment]
Hi @abathur ! Apologies for the late reply.

Disclaimer: I have very limited experience with Python and its ecosystem.

In an ideal world:

1. You would have access to a file containing the list of all the python packages ever released with their corresponding URL and hash.
1. You would have access to files describing consistent "snapshots" of packages, i.e. sets of packages (and their versions) known to work together.
1. You would have a way of knowing the dependencies of any package.

Your `requirements.txt` would then be part of (3), i.e. `requirements.txt` is just the list of dependencies for _your_ package.

Then you're in a great position because once you've specified a specific snapshot (e.g. tell Nix to use the "snapshot" file at URL `http://foo` with hash `1234bar`) you can look up all (transitive) dependencies that you'll need (for each (potentially unversioned) dependency in your `requirements.txt` you look up its own dependencies, and for each dependency you look up its dependencies, etc). That eventually gives you a set of all dependencies with their versions (the versions also come from the snapshot, e.g. (2)).

Then you install (rather you tell Nix to install) each (pinned) dependency by looking up the package's URL and hash in the "global package list", e.g. (1). Most likely you would use niv only to specify the url and hash of the global package list (1) and the particular snapshot you want to use (2).

---

This is basically how the Haskell infrastructure works. There is some machinery for parsing package files and figuring out the dependencies of a particular package; then it uses some snapshot (provided through nixpkgs) to lookup the needed dependencies. In this case actually the "global package list" is embedded in the snapshot: all packages are listed in the snapshot alongside their hashes (see [this](https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/development/haskell-modules/hackage-packages.nix)).

Now I've heard there are some issues with Python because the dependency list _may_ be dynamic, meaning you actually have to run some python script to figure what the dependencies are. I have no idea if any of the above is actually implemented for Python in nixpkgs; if not that'd be a fun project. The [python section](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md) of the nixpkgs guide is probably a good reference.

Hope this helps a bit!

**Comment by abathur** [comment]
No worries--thanks for the response. Not an urgent issue (for me, or Niv...) :)

I think I follow the first part of your response. I guess, in some sense, a shell.nix pulling specific handpicked package versions is already a sparse manual kludge for (1) and (2).

On the second part: I may be reading you wrong (or failing to make a leap/inference), but I think I probably fell short on illustrating one workflow pain point (and what I meant by bi-directional dependency workflows?) Rehashing in case it helps, but don't feel obliged to respond; I can also just take this to discourse :)

# Non-Nix environments
Nix solves a lot of dependency/version pain points for Nix environments (and your suggestions here would further improve the situation), but some others come along with using Nix in the development environment for projects that still have to support non-Nix installs, deployments, contributors, and so on. 

Still using Python specifics to illustrate here, but I think parts of this apply to idiomatic packaging for most languages. Unless I'm just projecting trauma from the Python ecosystem and everyone else's Nix tooling works fine :D

First I'll describe few Python deploy/install scenarios in non-Nix environments:
- When we deploy a Python web application to Heroku, the target nodes use pip to install dependencies from the app's `requirements.txt`. If this file doesn't pin everything in the dependency tree, it's not very reproducible, as unpinned (sub-)dependencies could shift per deploy. If it does pin everything, there's some extra maintenance overhead.
- When developing any given installable Python package/library, whether installed via pip or from source, the package's `setup.py` will specify (as you note, potentially dynamically) dependencies. These dependencies will usually be unpinned/abstract, or just have a version floor, unless there are pins/exclusion to cope with bugs/incompatibilities.
- Some projects include other `.txt` file that contributors can use to install dev-specific dependencies for linting/formatting/testing/etc.

# Main pain point
The main pain point that comes with developing in a Nix environment while still supporting non-Nix ones is maintaining the Nix and Python dependencies separately without introducing mistakes or letting them get out of sync. Possibilities:
- Keep the Python idioms as the source of truth. Whenever they change, generate Nix idioms (such as a `.nix` and [debatably?] `sources.json`) from the Python dependency spec. Many `<x>2nix` projects try this with varying degrees of success. I think this the ideal-universe approach, but none of the Python-to-Nix converters handled our Python web app without significant debug and manual edits to their outputs. Without a big quality leap in the converters (perhaps powered by the "ideal world" scenario you laid out?), doing this regularly is a non-starter. (We might be a complex edge case, but I didn't run into a single problem that didn't already have an open issue)
- Make the Nix idioms (whether a `.nix` file or [debatably?] `sources.json`) the source of truth and generate the Python idioms. Nix is well-situated for doing at least the templating part of this work repeatedly. This would still be missing a step/component for identifying/correcting problems.
- If there are intrinsic problems with translating from the idiomatic formats, there might be some benefit to an abstract source-of-truth format that can be separately translated to Nix and Python ecosystems. Again, this might (debatably?) include `sources.json`.

# Bi-directional dependency workflows
I also didn't do a great job unpacking what I meant by bi-directional dependency workflows and why I think it's an issue. 

1. The (inbound) Python-to-Nix dependency workflow to set up shell.nix files for developing a few apps and OSS projects was rocky, but worthwhile for things I work on a lot. This would still get tedious if I had to frequently rebase work against a project with frequent dependency updates and manually update shell.nix every time. 
2. I've also found myself avoiding minor contributions/fixes to projects I don't usually work on because I don't have the "typical" language toolchain and am leery of getting bogged down with debugging an inbound translation to `.nix` for significantly longer than the contribution itself will take. A low-friction workflow/toolchain here could be a Big Deal for developer experience.
3. I don't really have a non-manual reverse/outbound Nix-to-Python workflow to push updates back in generated versions of the Python dependency specs. I assume it's a matter of time until I mess one of these up.
4. Taken together, the lack of low-friction/high-reliability bi-directional toolchain makes me reluctant to share my Nix workflow with other team members or make it standard for a project.

This is roughly the intersection at which I imagined narrow(-ish) extensions or standalone tools that either convert a language-idiomatic dependency def into a niv command, or directly into the sources.json format, and likewise tools capable of reversing this back to the language-idiomatic dependency def. (I guess it could also support tools that can perform a _variety_ of utility tasks: scan nixpkgs for available versions, scan a language package manager like pip, swap a github/gitlab definition for a matching one in nixpkgs or language manager or vice-versa, enumerate dependency tree, check for known vulnerabilities, license compatibility checks, etc.)

**Comment by nmattia** [comment]
Hey @abathur , yeah let's continue on discourse :) Closing for now, don't hesitate to create new tickets if you have other questions!
